export interface Characters {
    name: string,
    age: string,
    isAlive: boolean,
    culture: string,
    father: string,
    gender: string,
    house: string,
    related: Array<string>,
    religion: string,
    siblings: Array<string>,
    spouse: string,
    titles: Array<string>,
    performer: string,
    image: string,
}
